rsmp-nordic/rsmp_schema

schemas/tlc/1.1/sxl.yaml

The S0033 is missing its table. Compare with https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html?highlight=source#id48
This PR adds it again

Add missing table in description of S0033

---

schemas/tlc/1.1/sxl.yaml

Max values seems to be missing for S0204 in the SXL when comparing it to the [online doc](https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html#s0204).
This PR adds them

Add max values in S0204

---

schemas/tlc/1.1/sxl.yaml

It it not needed for "source" in S0014 to be a **string_list**. It can be a **string** since only one time plan can be active at once in a TLC

S0014 :Change "source" to type "string"

---

schemas/tlc/1.1/sxl.yaml

Only one "traffic situation" can be active at once.
This PR changes **string_list** to **string** for the source attribute

S0015 'source' doesn't need to be string_list

---

schemas/tlc/1.1/sxl.yaml

We already have a separate field "optional: true", so there is no need to have this in the description field too.
The converter (sxl-tools) has been updated to use the "optional" field.

No need to include "Optional" in description field

---

schemas/tlc/1.1/sxl.yaml

A while ago we agreed on marking "extendedinputstatus" in S0003 and "extendedoutputstatus" in S0004 as deprecated in 1.1, Se https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/issues/74
They are noted as deprecated in the online doc and pdf, but the yaml file doesn't include this yet.
This PR suggest we adds `deprecated: true` for "extendedinputstatus" in S0003 and "extendedoutputstatus" in S0004

Mark "extendedinputstatus" and "extendedoutputstatus" as deprecated

---

schemas/tlc/1.1/sxl.yaml

In 1.1 M0010, M0011 and M0012 were marked as `reserved` for future use. They are currently not in use. They were originally meant to be used for coordination, but we ended up using Inputs instead due to questions regarding how they should be interpreted. Instead of marking them as deprecated it is better to make clarifications in a future release.
This PR marks them as reserved.

Mark M0010, M0011, M0012 as reserved for future use

---

schemas/tlc/1.1/sxl.yaml

This command does not use comma separated list. The intersection the command refers to is defined by the attribute 'intersection'
Also fix the description of the 'intersection'. See the M0001 in the [online doc](https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html#m0001) for reference.

M0001: Command does not use comma separated list

---

schemas/tlc/1.1/sxl.yaml

With SXL 1.1, the description text of S0096 was updated slightly. See the online doc for S0096
No need to include format and allowed max/min values in description text.

Update S0096 description text

---

schemas/tlc/1.1/sxl.yaml

The A0303 and A0304 should have priority level 2, since they are serious alarms.

Fix incorrect priority for A0303 and A0304

---

schemas/tlc/1.1/sxl.yaml

The last line of the description of S0011 appears to be missing

Fix truncated description text of S0011 (yellow flash)

---

schemas/tlc/1.1/sxl.yaml

Fix several issues with description M0013

---

schemas/tlc/1.1/sxl.yaml

The M0023 description should have "requires security code 2" in order to stay consistent with other commands

Fix truncated description text of M0023

---

schemas/tlc/1.1/sxl.yaml

Several statuses can have value -1 if no data could be measured
This PR changes "min: 0" to "min: -1".

Several statuses can have value -1 if no data could be measured

---

schemas/tlc/1.1/sxl.yaml

As discussed in https://github.com/rsmp-nordic/rsmp_schema/issues/27, functional_position and functional_state needs to be treated as a set of enums.
However, in the TLC SXL they are not used, so I suggest adding `enabled: false` instead of using a description text `functionalPosition and functionalState not used (set to null)`

Disable functional_position and functional_state

---

schemas/tlc/1.1/sxl.yaml

The maximum possible speed value in traffic counting S0202 is missing

Add missing max speed in traffic counting

---

schemas/tlc/1.1/sxl.yaml

I suggest adding support for markdown format in the description text. This allows more advanced formatting which will be shown in the online doc and pdf. Markdown is converted to RST (with sxl-tools) in the sxl repo.
This PR adds a link to the wiki in S0033 and updates the format of the table to markdown format (it used to be rst format)

Support markdown format in description text

---

schemas/tlc/1.1.1/sxl.yaml

Rename "stage" to route" in description of S0006.
Discussed in https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/issues/110 and https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/issues/145

S0006: Rename "stage" to "route"

---

schemas/tlc/1.1.1/sxl.yaml

Since RSMP 3.2.1 contains the definition of the timestamp type, there is no need to define the timestamp format everywhere its used.

Remove redudant timestamp format definitions in description fields

---

schemas/tlc/1.1.1/sxl.yaml

Discussion in https://github.com/rsmp-nordic/rsmp_validator/issues/270
Needs further discussion before merging

Add S0035 "emergency route" for supporting multiple active routes

---

schemas/tlc/1.1.1/sxl.yaml

As discussed in https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/issues/117, add ability to get the startup-mode for each intersection.

S0005: Add intersection to startup-mode

---

schemas/tlc/1.1.1/sxl.yaml

Clarify that emergency can be also used for other types of priorization in some cases

S0006,S0035: Add clarification of emergency route

---

schemas/tlc/1.1.1/sxl.yaml

S0018: Mark as deprecated. It has been marked deprecated since earlier, but this uses the correct yaml formatting

S0018: Mark as deprecated

---

schemas/tlc/1.2.1/sxl.yaml

M0001:
- intersection=0, means all intersections
- only the specified intersection is affected by command
Original issue here: https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/issues/160

Clarify m0001 regarding 'intersection'
